/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
import type * as presets from "./presets";
export type { presets };
export type { ILSP7DigitalAsset } from "./ILSP7DigitalAsset";
export type { LSP7DigitalAsset } from "./LSP7DigitalAsset";
export type { LSP7DigitalAssetCore } from "./LSP7DigitalAssetCore";
